//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion4Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntoCarga
    {
        public int IdPtoCarga { get; set; }
        public int Tipo { get; set; }
        public int CapMaxAutos { get; set; }
        public string VidaUtil { get; set; }
        public int IdEstacion { get; set; }
    
        public virtual Estacion Estacion { get; set; }
    }
}
